name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Run server lint
        run: |
          cd server
          npm run lint

      - name: Build server
        run: |
          cd server
          npm run build

      - name: Install frontend dependencies
        run: |
          cd src
          npm install

      - name: Run frontend lint
        run: |
          cd src
          npm run lint

      - name: Build frontend
        run: |
          cd src
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && success()
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
